export type Tour = {
  slug: string; title: string; location: string; duration: string; price: number; rating: number; reviews: number; category: string; badge?: string; image: string; description: string; highlights: string[];
}
export const tours: Tour[] = [
  { slug:'sigiriya-dambulla-day-tour', title:'Sigiriya & Dambulla Day Tour', location:'Sigiriya · Cultural Triangle', duration:'1 day', price:78, rating:4.9, reviews:142, category:'Cultural', badge:'Best seller', image:'https://www.yogawinetravel.com/wp-content/uploads/2016/05/Sigiriya-Lion-Rock-drone-photo-in-Sri-Lanka.jpg', description:'Walk through a 1,500-year-old rock fortress and discover Dambulla’s luminous cave temples.', highlights:['Private hotel pickup','Local guide','Cave temple visit'] },
  { slug:'ella-scenic-escape', title:'Ella Scenic Escape', location:'Ella · Hill Country', duration:'2 days', price:165, rating:4.9, reviews:98, category:'Nature', badge:'Popular', image:'/ella.jpg', description:'Misty mountains, emerald tea trails and the island’s most beautiful train journey.', highlights:['Nine Arch Bridge','Tea plantation','Scenic train ride'] },
  { slug:'kandy-cultural-experience', title:'Kandy Cultural Experience', location:'Kandy · Central Province', duration:'1 day', price:65, rating:4.8, reviews:86, category:'Cultural', image:'/kandy.jpg', description:'Temple rituals, lake walks and the living heritage of Sri Lanka’s hill capital.', highlights:['Temple of the Tooth','Cultural dance','Botanical gardens'] },
  { slug:'galle-fort-southern-coast', title:'Galle Fort & Southern Coast', location:'Galle · South Coast', duration:'1 day', price:72, rating:4.9, reviews:121, category:'Beach', badge:'New', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQkYFofAi4_M5HLnHyNLR6ciNJ3GuVdGA5dB0o-RmmIDyRK4W5R1R00hKR&s=10', description:'A slow day between colonial ramparts, hidden coves and the warm Indian Ocean.', highlights:['Galle Fort walk','Coastal lunch','Dutch Reformed Church'] },
  { slug:'yala-wildlife-safari', title:'Yala Wildlife Safari', location:'Yala · Southern Province', duration:'1 day', price:110, rating:4.7, reviews:74, category:'Wildlife', badge:'Adventure', image:'https://cdn.getyourguide.com/image/format=auto%2Cfit=crop%2Cgravity=auto%2Cquality=60%2Cwidth=400%2Cheight=265%2Cdpr=2/tour_img/96591ec77008733632f2a4f50c0f4fbc14289cd26b9b49c9d337cbd7ab3c6538.jpeg', description:'Track leopards, elephants and crocodiles across the island’s wildest landscapes.', highlights:['Morning safari','Park entrance','Naturalist guide'] },
  { slug:'mirissa-beach-experience', title:'Mirissa Beach Experience', location:'Mirissa · South Coast', duration:'1 day', price:59, rating:4.8, reviews:63, category:'Beach', image:'https://images.squarespace-cdn.com/content/v1/5a3bb03b4c326d76de73ddaa/1383f2a5-cd7b-4ded-8a16-508c8fca9790/The+Common+Wanderer-160.jpg', description:'Golden sands, a fresh seafood lunch and a sunset that lingers long after dinner.', highlights:['Beach time','Seafood lunch','Coconut Hill'] },
  { slug:'nuwara-eliya-tea-country', title:'Nuwara Eliya Tea Country', location:'Nuwara Eliya · Highlands', duration:'2 days', price:188, rating:4.8, reviews:55, category:'Nature', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoA6LR1sVNJWC3ODJ08yamjn7mmTHBg0FEWSiXmxRWD5smP-bZtQaIiCOr&s=10', description:'Cool mountain air, colonial charm and the story behind Ceylon’s finest leaves.', highlights:['Tea tasting','Gregory Lake','Waterfall stop'] },
  { slug:'bentota-beach-adventure', title:'Bentota Beach Adventure', location:'Bentota · West Coast', duration:'1 day', price:84, rating:4.7, reviews:48, category:'Adventure', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSGunchzx9S_j3MlT9cEP77FbOUAvJNpN0PhcLt9hgng&s=10', description:'A bright, breezy day of river safari, water sports and unhurried beach time.', highlights:['Madu River safari','Water sports','Beach resort'] },
  { slug:'grand-island-tour', title:'Sri Lanka Grand Island Tour', location:'Colombo to the coast', duration:'8 days', price:890, rating:5, reviews:39, category:'Private Tours', badge:'Signature', image:'https://images.unsplash.com/photo-1588598198321-9735fd5249b3?auto=format&fit=crop&w=800&q=75', description:'The essential island, paced beautifully from ancient cities to the southern sea.', highlights:['Private vehicle','8 nights','Local trip host'] },
  { slug:'colombo-city-explorer', title:'Colombo City Explorer', location:'Colombo · Western Province', duration:'1 day', price:48, rating:4.8, reviews:91, category:'Day Tours', image:'https://www.experiencetravelgroup.com/wp-content/uploads/2025/07/Pettah-colombo.jpg', description:'A local’s route through Colombo’s markets, galleries, mosques and oceanfront.', highlights:['Pettah market','Street food','Galle Face sunset'] },
  { slug:'udawalawe-elephant-country', title:'Udawalawe Elephant Country', location:'Udawalawe · South Central', duration:'1 day', price:96, rating:4.8, reviews:42, category:'Wildlife', image:'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/20/e8/11.jpg', description:'Meet Sri Lanka’s gentle giants in an open grassland sanctuary.', highlights:['Elephant sightings','Private jeep','Transit home visit'] },
  { slug:'ella-kandy-adventure', title:'Ella + Kandy Adventure', location:'Kandy to Ella', duration:'4 days', price:410, rating:4.9, reviews:37, category:'Adventure', badge:'Family friendly', image:'/ella.jpg', description:'A four-day highland route linking temples, tea, trails and unforgettable views.', highlights:['Scenic train','Cooking class','Little Adam’s Peak'] },
  { slug:'south-coast-explorer', title:'South Coast Explorer', location:'Galle to Mirissa', duration:'3 days', price:285, rating:4.9, reviews:31, category:'Beach', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCZO51rYeXHw0o1PpMYxIrAVeHGtEObNvkiKIc07fvbnIOBMFYLVWG4Bw&s=10', description:'The relaxed southern rhythm: fort towns, surf beaches and fishing villages.', highlights:['Galle Fort','Whale watching','Beach stays'] },
  { slug:'honeymoon-escape', title:'Sri Lanka Honeymoon Escape', location:'Ella · Galle · South Coast', duration:'7 days', price:1180, rating:5, reviews:26, category:'Honeymoon', badge:'Romantic', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqCqfYlBtOUpEPWw-pAPa_weho70DwqocC3l01h1q5awzMteoHiLPmU6gK&s=10', description:'Seven intimate days of boutique stays, private moments and island beauty.', highlights:['Boutique hotels','Couples’ picnic','Private vehicle'] },
  { slug:'complete-sri-lanka-journey', title:'Complete Sri Lanka 10-Day Journey', location:'Island-wide', duration:'10 days', price:1290, rating:4.9, reviews:44, category:'Multi-Day Tours', badge:'Signature', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSusVEWuZ8piBrhKDF74cilc7W6HeCvxOWG2yqwLgbQzIQZ_DznchH3HgTz&s=10', description:'A considered, comfortable introduction to Sri Lanka’s most rewarding places.', highlights:['All transport','Curated hotels','24/7 support'] },
]
export const destinations = [
  { name:'Ella', slug:'ella', eyebrow:'Highland air', description:'A green mountain town of tea trails, cloud forests and slow mornings.', image:'https://littlewanderbook.com/wp-content/uploads/2020/11/Ella-Sri-Lanka-8-van-11-scaled.jpg', best:'January – April', attractions:'Nine Arch Bridge · Little Adam’s Peak · Tea country' },
  { name:'Sigiriya', slug:'sigiriya', eyebrow:'Ancient wonder', description:'Climb into the story of an island kingdom beneath wide blue skies.', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlqSNy-XJrfeghowyswU6WqwmzmVsHQ2HFbKbl5DAvnE3bAPexXhJDsB4&s=10', best:'January – September', attractions:'Lion Rock · Dambulla caves · Minneriya' },
  { name:'Galle', slug:'galle', eyebrow:'Southern soul', description:'A sun-warmed fort city where Dutch walls meet the Indian Ocean.', image:'/galle.jpeg', best:'December – April', attractions:'Galle Fort · Unawatuna · Jungle Beach' },
  { name:'Yala', slug:'yala', eyebrow:'Wild at heart', description:'Open plains, ancient forests and the thrilling chance of a leopard sighting.', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKqXjP0ytsMGjS1vu2z60ZVsdEfPu-3PY63g-tXBfCoA&s=10', best:'February – June', attractions:'Yala National Park · Kataragama · Bundala' },
  { name:'Kandy', slug:'kandy', eyebrow:'Cultural capital', description:'A lake-ringed city where ritual, craft and rainforest meet.', image:'https://rootsabroadtravel.com/wp-content/uploads/2024/01/The-Best-Things-to-Do-in-Kandy-Sri-Lanka.jpg', best:'January – April', attractions:'Temple of the Tooth · Peradeniya · Spice gardens' },
  { name:'Mirissa', slug:'mirissa', eyebrow:'Ocean days', description:'A crescent beach made for early boats, long lunches and barefoot sunsets.', image:'/mirissa.jpg', best:'November – April', attractions:'Whale watching · Coconut Hill · Weligama surf' },
]
export const bikes = [
  { name:'Honda Dio 110', type:'City scooter', cc:110, price:7, weekly:49, monthly:210, deposit:0, image:'/dio.jpg' },
  { name:'Ntorq 125', type:'Premium motorcycle', cc:125, price:10, weekly:70, monthly:300, deposit:0, image:'/ntorq.png' },
  { name:'Honda Navi ', type:'Navi (Honda)', cc:110, price:5, weekly:35, monthly:150, deposit:0, image:'/navi.jpeg' },
  { name:'Grazia 125', type:'Comfort scooter', cc:125, price:8, weekly:56, monthly:240, deposit:0, image:'/grazia.jpeg' },
  { name:'Bajaj N160', type:'Manual', cc:160, price:9, weekly:63, monthly:270, deposit:0, image:'/n160.avif' },
  { name:'ADV160', type:'Road motorcycle', cc:150, price:12, weekly:84, monthly:360, deposit:0, image:'/adv.jpeg' },
]
export const activities = [
  { title:'Whale Watching at Mirissa', location:'Mirissa', duration:'4 hours', price:42, rating:4.8, image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzXqAbqffqSHvamHprtSFlHY6N503e6oJRys5XVodVNA&s=10' },
  { title:'Tea Trails & Tasting', location:'Nuwara Eliya', duration:'3 hours', price:28, rating:4.9, image:'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=700&q=75' },
  { title:'Sunrise Hike to Ella Rock', location:'Ella', duration:'5 hours', price:35, rating:4.9, image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxRVxMgf5NoN-ixUoFra6GMDR3Ez226G0iPJE_9ddjTsj-NDaOnBMwkOI&s=10' },
  { title:'Galle Fort Walking Tour', location:'Galle', duration:'2 hours', price:24, rating:4.9, image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk9MzhMGjxdF7kaEmRxwhkBYeWoyQM2b1fjPnM8CTbxcHzl1Iaqr-fs7gs&s=10' },
  { title:'Surfing Lesson', location:'Weligama', duration:'2 hours', price:30, rating:4.9, image:'https://lapoint.b-cdn.net/image/6360sXUgluyJT1OgpmzLA6/d83d673381449f4120d57c0b1dcb4dd1/lapoint-surfcamp-sri-lanka-lovisa-herfindal-1.jpg?fm=jpg&fl=progressive&w=1920&q=75' },
  { title:'Jet Ski Ride', location:'Bentota', duration:'30 minutes', price:45, rating:4.8, image:'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/17/06/2a.jpg' },
]
export const reviews = [
  { name:'Sophie', country:'United Kingdom', quote:'Every detail felt thoughtful. Our guide knew exactly when to slow down, and the island completely surprised us.', tour:'Ella Scenic Escape' },
  { name:'Marco', country:'Italy', quote:'The easiest way to see Sri Lanka without losing the freedom to wander. Our bike was immaculate and the advice was gold.', tour:'Bike rental · Colombo' },
  { name:'Amina', country:'United Arab Emirates', quote:'From airport pickup to our final sunset in Galle, Bola made a complicated family trip feel wonderfully simple.', tour:'Complete Sri Lanka Journey' },
  { name:'Anastasia', country:'Russia', quote:'We rented a scooter for Galle and Mirissa and everything was easy: helmets, WhatsApp support and clear advice for the coastal road.', tour:'Mirissa Galle Bike Rental' },
  { name:'Dmitry', country:'Russia', quote:'The Galle Fort tour felt personal, not rushed. Our guide knew the quiet corners, good coffee stops and the best time for photos.', tour:'Galle Fort & Southern Coast' },
  { name:'Elena', country:'Russia', quote:'Bola helped us plan Ella, Yala and the south coast with a smooth pace. It felt safe, warm and very local.', tour:'Custom Sri Lanka Tour' },
  { name:'James', country:'Australia', quote:'The motorbike pickup in Galle was fast and the bike was exactly as promised. Perfect for exploring Mirissa and Hikkaduwa.', tour:'Galle Bike Rental' },
  { name:'Nora', country:'Germany', quote:'Our south coast days were beautifully organised, from whale watching in Mirissa to sunset walks inside Galle Fort.', tour:'South Coast Explorer' },
  { name:'Priya', country:'India', quote:'The team answered quickly, adjusted our route and made the family trip feel calm even with kids and changing plans.', tour:'Family Custom Tour' },
  { name:'Lucas', country:'France', quote:'Simple booking, fair price and honest local tips. The scooter made the beaches around Galle and Mirissa much easier to enjoy.', tour:'Scooter Rental · Galle' },
]
export const faqs = [
  ['Do I need a driving licence to rent a bike?', 'Yes. You will need your home-country licence and an International Driving Permit or Sri Lankan temporary permit. We explain the process before you ride.'],
  ['Can I book a private or custom tour?', 'Absolutely. Every tour can be made private, and our Build Your Trip planner is a useful starting point for a route shaped around your pace.'],
  ['Where are your shops?', 'Bola Tours shops are in Galle, Kalutara, Ella and Hikkaduwa. Choose the closest shop when booking a bike or tour.'],
  ['What happens if my flight is delayed?', 'Share your flight number with us and we monitor arrivals. Your driver will adjust the meeting time when possible.'],
  ['Are helmets provided with rentals?', 'Two quality helmets are included with every motorcycle and scooter rental. Phone mounts and luggage racks are available as extras.'],
  ['Can I rent a bike for one month?', 'Yes. Monthly rates are available on selected models, with flexible delivery and collection from Galle, Kalutara, Ella and Hikkaduwa.'],
]
